steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - Dockerfile.streamlit
      - '-t'
      - 'gcr.io/$PROJECT_ID/streamlit-custom-model-renato:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/streamlit-custom-model-renato:$SHORT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/streamlit-custom-model-renato:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY